import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '@/components/header/Header'
import Providers from '@/components/Providers'
import DrawerButton from '@/components/DrawerButton'
import Sidebar from '@/components/Sidebar'


const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create ecommerce',
  description: 'Generated by create ecommerce',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
      <html lang="en">
        <body className={geistMono.className}>
          <Providers>
            <div className="drawer">
              <DrawerButton />
              <div className="drawer-content">
                {/* Page content here */}
                <div className="min-h-screen flex flex-col">
                  <Header />
                  {children}
                  <footer className="footer footer-center p-4 bg-base-300 text-base-content">
                    <p>
                      Copyright © 2023 - All right reserved by{' '}
                      {process.env.NEXT_PUBLIC_APP_NAME || 'Next Shop'}
                    </p>
                  </footer>
                </div>
              </div>
              <div className="drawer-side">
                <label
                  htmlFor="my-drawer"
                  aria-label="close sidebar"
                  className="drawer-overlay"
                ></label>
                <Sidebar />
              </div>
            </div>
          </Providers>
        </body>
      </html>
    )
}
